---
x-default-container: &default-container
  #user: 1000:1000
  group_add:
    - "1000"
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Toronto
  restart: unless-stopped

x-mediarr-container: &mediarr-container
  <<: *default-container
  volumes:
    - mediarr-data:/mnt/mediarr/
    - mediarr-downloads:/data/downloads/
volumes:
  mediarr-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/ark/mediarr/
  mediarr-downloads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/ark/mediarr/downloads/
services:
  jellyfin:
    image: ghcr.io/jellyfin/jellyfin
    <<: *mediarr-container
    container_name: jellyfin
    volumes:
      - /mnt/ark/mediarr/jellyfin/config:/config
      - /mnt/ark/mediarr/jellyfin/cache:/cache
      - /mnt/ark/mediarr/tv-shows:/mnt/tv-shows
    ports:
      - 8096:8096
#    environment: 
#      - JELLYFIN_PublishedServerUrl="http://exmaple.com"
