---
x-default-container: &default-container
  user: 704170789:133610176
  group_add: 
    - "109"
  environment:
    - PUID=1000 
    - PGID=1000 
    - TZ=America/Toronto 
  restart: unless-stopped

  # containers on the mediarr nework, also have access to specific volumes
x-mediarr-container: &mediarr-container
  <<: *default-container
  networks:
    - mediarr
  volumes: 
    - mediarr-data:/data/mediarr/
    - mediarr-downloads:/data/downloads/
networks: 
  mediarr: 
    driver: bridge
volumes:
  mediarr-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/ark/mediarr/
  mediarr-downloads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/ark/mediar/downloads/
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    <<: *mediarr-container
    container_name: sonarr
    volumes:
      - /mnt/ark/mediarr/sonarr:/config
    ports:
      - 8989:8989
    restart: unless-stopped

