---
x-default-container: &default-container
  #user: 1000:1000
  group_add: 
    - "1000"
  environment:
    - PUID=1000 
    - PGID=1000 
    - TZ=America/Toronto 
  restart: unless-stopped
  # containers on the mediarr nework, also have access to specific volumes
x-mediarr-container: &mediarr-container
  <<: *default-container
  volumes: 
    - mediarr-data:/data/mediarr/
    - mediarr-downloads:/data/downloads/
volumes:
  mediarr-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/ark/mediarr/
  mediarr-downloads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/ark/mediarr/downloads/
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    <<: *mediarr-container
    container_name: sonarr
    volumes:
      - /mnt/ark/mediarr/sonarr:/config
    ports:
      - 8989:8989

  radarr: 
    image: lscr.io/linuxserver/radarr:latest
    <<: *mediarr-container
    container_name: radarr
    volumes:
      - /mnt/ark/mediarr/radarr:/config
    ports:
      - 7878:7878
  
  bazarr: 
    <<: *mediarr-container
    image: lscr.io/linuxserver/bazarr:latest 
    container_name: bazarr 
    hostname: bazarr 
    volumes: 
      - /mnt/ark/mediarr/bazarr:/config 
    ports: 
      - 6767:6767
    depends_on: 
      - sonarr 
      - radarr
  
  jellyseerr: 
    <<: *mediarr-container
    image: fallenbagel/jellyseerr:latest 
    container_name: jellyseerr 
    hostname: jellyseerr 
    ports: 
      - 5055:5055 
    volumes: 
      - /mnt/ark/mediarr/jellyseerr:/app/config 
    depends_on: 
      - sonarr 
      - radarr
  
  prowlarr: 
    <<: *mediarr-container
    image: linuxserver/prowlarr:latest 
    container_name: prowlarr 
    hostname: prowlarr 
    volumes: 
      - /mnt/ark/mediarr/prowlarr:/config 
    ports: 
      - 9696:9696
  
  flaresolverr: 
    <<: *mediarr-container
    image: ghcr.io/flaresolverr/flaresolverr:latest 
    container_name: flaresolverr 
    hostname: flaresolverr 
    environment: 
      - LOG_LEVEL=${LOG_LEVEL:-info} 
      - LOG_HTML=${LOG_HTML:-false} 
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none} 
    ports:
    - 8191:8191

  qbittorrent: 
    <<: *mediarr-container
    image: lscr.io/linuxserver/qbittorrent:latest 
    container_name: qbittorrent 
    hostname: qbittorrent 
    environment:
      - WEBUI_PORT=8080 
    volumes: 
      - /mnt/ark/mediarr/qbittorrent:/config
    ports: 
      - 8080:8080 
      - 6881:6881 
      - 6881:6881/udp
